#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.73:8888/school?useServerPrepStmts=true&cachePrepStmts=true
#    username: china
#    password: chinese
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximumPoolSize: 1
datasource:
  schema-a:
    jdbc-url: jdbc:mysql://localhost:3306/sample
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 1
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  schema-b:
    jdbc-url: jdbc:mysql://localhost:3306/sample2
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 1
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true