## /actuator 开放 beans caches conditions configprops env flyway health httptrace metrics mappings scheduledtasks sessions shutdown threaddump
#management:
#    endpoint:
#        health:
#            show-details: always
#    endpoints:
#        web:
#            exposure:
#                include: '*'
#    server:
#        address: 127.0.0.1
spring:
    application:
        admin:
            enabled: true
    servlet:
        multipart:
            max-file-size: -1
    redis:
        host: redis
        port: 6379
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 2
                shutdown-timeout: 100ms
    cache:
        type: CAFFEINE
        cache-names: demoCache
        caffeine:
            spec: maximumSize=500,expireAfterAccess=600s
datasource:
    schema-primary:
        jdbc-url: jdbc:mysql://mysql:3306/primary?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: china
        password: chinese
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 1
        data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            rewriteBatchedStatements: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
    schema-secondary:
        jdbc-url: jdbc:mysql://mysql:3306/secondary?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: china
        password: chinese
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 1
        data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            rewriteBatchedStatements: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
    schema-quartz:
        jdbc-url: jdbc:mysql://mysql:3306/quartz?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: china
        password: chinese
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 1
        data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            rewriteBatchedStatements: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-handlers-package: app.type.handler
    mapper-locations: app/dao/*/*.xml