#spring:
#  application:
#    admin:
#      enabled: true
# /actuator开放 beans caches conditions configprops env flyway health httptrace metrics mappings scheduledtasks sessions shutdown threaddump
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    address: 127.0.0.1
spring:
  servlet:
    multipart:
      max-file-size: -1
datasource:
  schema-a:
    jdbc-url: jdbc:mysql://localhost/sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  schema-b:
    jdbc-url: jdbc:mysql://localhost:3000/sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
