#spring:
#  application:
#    admin:
#      enabled: true
# /actuator开放 beans caches conditions configprops env flyway health httptrace metrics mappings scheduledtasks sessions shutdown threaddump
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    address: 127.0.0.1
spring:
  servlet:
    multipart:
      max-file-size: -1
  redis:
    host: redis
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        shutdown-timeout: 100ms
  cache:
    redis:
      time-to-live: 3600
datasource:
  schema-a:
    jdbc-url: jdbc:mysql://mysql/sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  schema-b:
    jdbc-url: jdbc:mysql://mysql:3000/sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: china
    password: chinese
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-handlers-package: app.type.handler
#  mapper-locations: app/dao/ScheduleJobDao.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: app.type.handler
  mapper-locations: app/dao/ScheduleJobDao.xml
