spring:
    redis:
        host: wsl2
        port: 6379
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 2
                shutdown-timeout: 100ms